kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-queuecon-deployment
  namespace: prod-stablecog
  labels:
    app: sc-queuecon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-queuecon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sc-queuecon
    spec:
      containers:
        - name: sc-queuecon
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 512Mi
          command: ["/bin/sh", "-c"]
          args: ["/app/quecon"]
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: sc-go
          env:
            - name: PUBLIC_SUPABASE_REFERENCE_ID
              value: jaqefzjqokaemzyvjcew
            - name: PRODUCTION
              value: "true"
            - name: PUBLIC_API_URL
              value: https://api.stablecog.com
            - name: PRIVATE_API_URL
              value: http://server-service.prod-stablecog:13337
            - name: BUCKET_BASE_URL
              value: https://b.stablecog.com
            - name: LOKI_APPLICATION_LABEL
              value: sc-quecon
